package com.heaven.soulmate.chat.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * Created by legol on 2015/11/22.
 */
@JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
@JsonInclude(value = JsonInclude.Include.NON_EMPTY)
public class ChatAckMessage {
    @JsonProperty("message_id")
    private long messageId; // this one is generated by db rather than passing in from the client

    @JsonProperty("uid")
    private long uid;

    @JsonProperty("token")
    private String token;

    public long getMessageId() {
        return messageId;
    }

    public long getUid() {
        return uid;
    }

    public String getToken() {
        return token;
    }

    public void setMessageId(long messageId) {
        this.messageId = messageId;
    }

    public void setUid(long uid) {
        this.uid = uid;
    }

    public void setToken(String token) {
        this.token = token;
    }
}
